name: ann-lstm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
